### ISSUE TITLE
How to work close connection

### ISSUE THREAD

**Issue by misterwolf** [websocket-rails/websocket-rails#303]
Hi to all!
Maybe I didn't go in the right documentation but I still haven't understood well the client_disconnected method.

What parameters arrive in server method when the client call the event "close"?
and then, will the client receive a callback from the server after this call?

And I also want ask: I saw in the issues that I can forcibly close a connection from the server without any client call. Is there a full example of that method?

Thanks!

Dario

**Comment by dcurletti** [comment]
Did you ever find an answer to your question?  I'm replacing ActionController:Live with websockets and was wondering how to close the connection on user disconnect.

**Comment by moaa** [comment]
I'm not sure I completely understand the question/issue here.. but it should be closed automatically .. also you can bind to the `connection_closed` event, both inside `config/events.rb` and in the javascript dispatcher.

Since this is an ancient issue, I'm going to close it out.  Feel free to create a new one if you're still having issues or have more questions.
