### ISSUE TITLE
Standalone Server Serves my entire application

### ISSUE THREAD

**Issue by varun-raj** [websocket-rails/websocket-rails#319]
Whenever I tried to run websocket-rails in standalone mode, it serves all of my application's request.
(Apart from localhost:3001/websocket)

**Comment by Oxynum** [comment]
Give more context to your issue, what have you ran exactly, what server are you using, etc... ?

**Comment by varun-raj** [comment]
I'm using passenger for my main app. So when i try the sockets within the main app it's not working. Then i thought of having a seperate standalone server for WebSocket that will serve this app.
Is this possible ?

**Comment by moaa** [comment]
Yes, sadly this is a side effect of standalone.  Because there are so many rack servers (Puma, Unicorn, Thin, Sinatra, and others), standalone mode is a way to load up EventMachine outside of whatever server your app uses.  You can think of standalone mode as your app running inside Thin...  a work around to restrict standalone from serving other portions of your app would be to proxy `/websocket` requests via Nginx and restrict access to your standalone upstream.

Hope this makes sense.
