### ISSUE TITLE
crash when set config.synchronize = true,help

### ISSUE THREAD

**Issue by aeroyu** [websocket-rails/websocket-rails#362]
my settings is

config.synchronize = true
config.redis_options = {:host => '127.0.0.1', :port => '6380'}

ruby 2.2.1 rails 4.1.6
and run with this setting,will crash 
/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection': Error connecting to Redis on 192.168.37.4:6380 (Errno::ECONNREFUSED) (Redis::CannotConnectError)

is project active？

**Comment by aeroyu** [comment]
i set the redis to 3.2.0 and solve this question，and the new question is
/Users/janyu/.rvm/gems/ruby-2.2.2/gems/json-1.8.2/lib/json/common.rb:155:in `initialize': no implicit conversion of Fixnum into String (TypeError)
	from /Users/janyu/.rvm/gems/ruby-2.2.2/gems/json-1.8.2/lib/json/common.rb:155:in `new'
	from /Users/janyu/.rvm/gems/ruby-2.2.2/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	from /Users/janyu/.rvm/gems/ruby-2.2.2/gems/websocket-rails-0.7.0/lib/websocket_rails/synchronization.rb:167:in `block in find_use

i find the souce in synchronization.rb method find_user and debug it
def find_user(identifier)
      Fiber.new do
        raw_user = redis.hget('websocket_rails.users', identifier)
        raw_user ? JSON.parse(raw_user) : nil
      end.resume
end

i find raw_user can not get right,and if i run in console to get redis is right
any one help~

**Comment by Qqwy** [comment]
I was struggling with the same problem.

Pegging the Redis version to `3.2.0` in my Gemfile cleared the first error, and showed the second.

I added the following monkey patch to the head of `config/initializers/websocket_rails.rb`:

    module WebsocketRails
      class Synchronization
    
    
        def find_user(identifier)
          Fiber.new do
            begin
              raw_user = redis.hget('websocket_rails.users', identifier)
              raw_user ? JSON.parse(raw_user) : nil
            rescue => e
              puts "WebsocketRails::Synchronization#find_user threw error:"
              puts e.inspect
              puts "RAW USER:"
              puts raw_user.inspect
              puts "IDENTIFIER:"
              puts identifier.inspect
              puts "REDIS:"
              puts redis.inspect
              puts "Returning `nil` instead."
    
              nil #Return nil in this case
            end
          end.resume
        end
    
    
      end
    end


By logging, it seems that this error only happens when attempting to serve a MissingConnection. With this block in place (you can of course remove all the puts statemements), it will not crash, and I have not spotted any broken behaviour.


Of course, I still have the hope that one of the original authors of this Gem could look at this problem. Personally I find ActionCable too immature for real-world usage right now, and I do not like some of the design choices made there, so I really do hope that this gem will be kept supported.

**Comment by kumaresan-rails** [comment]
Thanks @Qqwy. i'm banging my head for 2 days. Great help indeed.
