### ISSUE TITLE
websocket_rails.log keep growing

### ISSUE THREAD

**Issue by bl4d3** [websocket-rails/websocket-rails#79]
Hi, my websocket_rails.log is very large and keep growing, i'm using the gem in prod environment and i tried to disable the log in this way

``` ruby
WebsocketRails.setup do |config|
  config.log_internal_events = false
  config.standalone = true
  config.synchronize = false
end
```

I thought   config.log_internal_events = false it was enough but keep logging, how to disable this log?
thank you

**Comment by Sharespot** [comment]
I'm having the same issue here. It grows more than 100M/day!!!

**Comment by Sharespot** [comment]
I tried logrotate but for some reason this config:

/home/production/magikey_server/log/websocket_rails.log{
size=20M
missingok
rotate 7
compress
delaycompress
notifempty
copytruncate
}

is not rotating the file at 20M. It actually grows too much before rotating. I've also tried rotating it daily but the file grows too much even in a day...

Anyway, I'm not using this file and it's really annoying. Just to make sure, in order to disable it I must put config.logger = Logger.new("/dev/null") on events.rb ?! The same file I subscribe events to the controller's actions?
